/**
 * Centralized route definitions.
 * Prevents typos and enables easy refactoring of route paths.
 */

export const ROUTES = {
  // Public routes
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  
  // Protected routes
  DASHBOARD: '/dashboard',
  COMPANIES: '/companies',
  PROJECTS: '/projects',
  PROJECT_DETAIL: '/projects/:id',
  SITES: '/sites',
  SITE_DETAIL: '/sites/:id',
  LEADS: '/leads',
  CLIENTS: '/clients',
  EMPLOYEES: '/employees',
  HR: '/hr',
  INVENTORY: '/inventory',
  NOTIFICATIONS: '/notifications',
  
  // CRM routes
  CRM_LEADS: '/crm/leads',
  CRM_LEAD_DETAIL: '/crm/leads/:id',
  CRM_CLIENTS: '/crm/clients',
  CRM_CLIENT_DETAIL: '/crm/clients/:id',
  CRM_PIPELINE: '/crm/pipeline',
  CRM_MEETINGS: '/crm/meetings',
  CRM_FOLLOWUPS: '/crm/followups',
  
  // Platform Owner routes
  PLATFORM: '/platform',
  PLATFORM_COMPANIES: '/platform/companies',
  PLATFORM_PLANS: '/platform/plans',
  PLATFORM_SUBSCRIPTIONS: '/platform/subscriptions',
  PLATFORM_COUPONS: '/platform/coupons',
  PLATFORM_ANALYTICS: '/platform/analytics',
  PLATFORM_SETTINGS: '/platform/settings',
  
  // Company Admin routes
  COMPANY: '/company',
  COMPANY_USERS: '/company/users',
  COMPANY_EMPLOYEES: '/company/employees',
  COMPANY_ROLES: '/company/roles',
  COMPANY_DEPARTMENTS: '/company/departments',
  COMPANY_PROFILE: '/company/profile',
  COMPANY_MODULES: '/company/modules',
  COMPANY_BRANDING: '/company/branding',
  COMPANY_SETTINGS: '/company/settings',
  
  // Settings
  SETTINGS: '/settings',
  PROFILE: '/settings/profile',
  SECURITY: '/settings/security',
  BILLING: '/settings/billing',
  
  // Error pages
  NOT_FOUND: '/404',
  SERVER_ERROR: '/500',
  
  // Redirects
  LOGIN_REDIRECT: '/dashboard',
};

/**
 * Route configuration with metadata for navigation and route guards.
 */
export const ROUTE_CONFIG = {
  [ROUTES.HOME]: {
    path: ROUTES.HOME,
    label: 'Home',
    isPublic: true,
  },
  [ROUTES.LOGIN]: {
    path: ROUTES.LOGIN,
    label: 'Login',
    isPublic: true,
    requiresAuth: false,
  },
  [ROUTES.REGISTER]: {
    path: ROUTES.REGISTER,
    label: 'Register',
    isPublic: true,
    requiresAuth: false,
  },
  [ROUTES.DASHBOARD]: {
    path: ROUTES.DASHBOARD,
    label: 'Dashboard',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.COMPANIES]: {
    path: ROUTES.COMPANIES,
    label: 'Companies',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.PROJECTS]: {
    path: ROUTES.PROJECTS,
    label: 'Projects',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.SITES]: {
    path: ROUTES.SITES,
    label: 'Sites',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.LEADS]: {
    path: ROUTES.LEADS,
    label: 'Leads',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.EMPLOYEES]: {
    path: ROUTES.EMPLOYEES,
    label: 'Employees',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.HR]: {
    path: ROUTES.HR,
    label: 'HR Management',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.INVENTORY]: {
    path: ROUTES.INVENTORY,
    label: 'Inventory',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.CRM_LEADS]: {
    path: ROUTES.CRM_LEADS,
    label: 'Leads',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.CRM_CLIENTS]: {
    path: ROUTES.CRM_CLIENTS,
    label: 'Clients',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.CRM_PIPELINE]: {
    path: ROUTES.CRM_PIPELINE,
    label: 'Pipeline',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.CRM_MEETINGS]: {
    path: ROUTES.CRM_MEETINGS,
    label: 'Meetings',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.CRM_FOLLOWUPS]: {
    path: ROUTES.CRM_FOLLOWUPS,
    label: 'Follow Ups',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.SETTINGS]: {
    path: ROUTES.SETTINGS,
    label: 'Settings',
    isPublic: false,
    requiresAuth: true,
    layout: 'dashboard',
  },
  [ROUTES.PLATFORM]: {
    path: ROUTES.PLATFORM,
    label: 'Platform',
    isPublic: false,
    requiresAuth: true,
    layout: 'platform',
    requiresPlatformOwner: true,
  },
  [ROUTES.PLATFORM_COMPANIES]: {
    path: ROUTES.PLATFORM_COMPANIES,
    label: 'Companies',
    isPublic: false,
    requiresAuth: true,
    layout: 'platform',
    requiresPlatformOwner: true,
  },
  [ROUTES.PLATFORM_PLANS]: {
    path: ROUTES.PLATFORM_PLANS,
    label: 'Plans',
    isPublic: false,
    requiresAuth: true,
    layout: 'platform',
    requiresPlatformOwner: true,
  },
  [ROUTES.PLATFORM_SUBSCRIPTIONS]: {
    path: ROUTES.PLATFORM_SUBSCRIPTIONS,
    label: 'Subscriptions',
    isPublic: false,
    requiresAuth: true,
    layout: 'platform',
    requiresPlatformOwner: true,
  },
  [ROUTES.PLATFORM_COUPONS]: {
    path: ROUTES.PLATFORM_COUPONS,
    label: 'Coupons',
    isPublic: false,
    requiresAuth: true,
    layout: 'platform',
    requiresPlatformOwner: true,
  },
  [ROUTES.PLATFORM_ANALYTICS]: {
    path: ROUTES.PLATFORM_ANALYTICS,
    label: 'Analytics',
    isPublic: false,
    requiresAuth: true,
    layout: 'platform',
    requiresPlatformOwner: true,
  },
  [ROUTES.PLATFORM_SETTINGS]: {
    path: ROUTES.PLATFORM_SETTINGS,
    label: 'Settings',
    isPublic: false,
    requiresAuth: true,
    layout: 'platform',
    requiresPlatformOwner: true,
  },
  [ROUTES.COMPANY]: {
    path: ROUTES.COMPANY,
    label: 'Dashboard',
    isPublic: false,
    requiresAuth: true,
    layout: 'company',
    requiresCompanyAdmin: true,
  },
  [ROUTES.COMPANY_USERS]: {
    path: ROUTES.COMPANY_USERS,
    label: 'Users',
    isPublic: false,
    requiresAuth: true,
    layout: 'company',
    requiresCompanyAdmin: true,
  },
  [ROUTES.COMPANY_EMPLOYEES]: {
    path: ROUTES.COMPANY_EMPLOYEES,
    label: 'Employees',
    isPublic: false,
    requiresAuth: true,
    layout: 'company',
    requiresCompanyAdmin: true,
  },
  [ROUTES.COMPANY_ROLES]: {
    path: ROUTES.COMPANY_ROLES,
    label: 'Roles',
    isPublic: false,
    requiresAuth: true,
    layout: 'company',
    requiresCompanyAdmin: true,
  },
  [ROUTES.COMPANY_DEPARTMENTS]: {
    path: ROUTES.COMPANY_DEPARTMENTS,
    label: 'Departments',
    isPublic: false,
    requiresAuth: true,
    layout: 'company',
    requiresCompanyAdmin: true,
  },
  [ROUTES.COMPANY_PROFILE]: {
    path: ROUTES.COMPANY_PROFILE,
    label: 'Company Profile',
    isPublic: false,
    requiresAuth: true,
    layout: 'company',
    requiresCompanyAdmin: true,
  },
  [ROUTES.COMPANY_MODULES]: {
    path: ROUTES.COMPANY_MODULES,
    label: 'Modules',
    isPublic: false,
    requiresAuth: true,
    layout: 'company',
    requiresCompanyAdmin: true,
  },
  [ROUTES.COMPANY_BRANDING]: {
    path: ROUTES.COMPANY_BRANDING,
    label: 'Branding',
    isPublic: false,
    requiresAuth: true,
    layout: 'company',
    requiresCompanyAdmin: true,
  },
  [ROUTES.COMPANY_SETTINGS]: {
    path: ROUTES.COMPANY_SETTINGS,
    label: 'Settings',
    isPublic: false,
    requiresAuth: true,
    layout: 'company',
    requiresCompanyAdmin: true,
  },
};